### ISSUE TITLE
New project ionic2 failed on build error , the module "Unexpected value"

### ISSUE THREAD

**Issue by macdosi** [driftyco/ionic2-module-template#1]
I've opened new ionic2 app by using command "ionic start ionic2 --v2"  , I've installed "Ionic2 Module Template" from 
https://github.com/driftyco/ionic2-module-template
I run "ionic serve" the app open in browser showing "my-component" from the imported module , but as I run "ionic build android" I get error
>[12:27:36]  Error: Unexpected value 'MyModule' imported by the module 'AppModule' 
[12:27:36]  ngc failed 
[12:27:36]  ionic-app-script task: "build" 
[12:27:36]  Error: Error 
How come ?

**Comment by Yermo** [comment]
I am having the same issue however in my case even 'ionic serve' fails to run and generates the same error (after I turn on console messages). There is a stackoverflow question that seems to indicate it's more wide spread than just this module: http://stackoverflow.com/questions/40391443/how-to-structure-a-shared-npm-module-for-angular-2-ionic-2-apps

Is there an app somewhere that demonstrates how to correctly refer to this repository from the dependencies in packages.json and get it to 'just work' after an npm install/ionic serve? 

Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.2
Ionic CLI Version: 2.1.8
Ionic App Lib Version: 2.1.4
Ionic App Scripts Version: 0.0.43
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 3.13
Node Version: v5.6.0
Xcode version: Not installed

**Comment by mlynch** [comment]
Hey all, this project isn't quite ready. I need to add support for NGC builds yet

**Comment by mlynch** [comment]
All fixed up, thanks! Cheers to @ihadeed and his https://github.com/zyramedia/ionic-image-loader for providing a nice starting point for an ng2 module w/ ngc support.

**Comment by juansaab** [comment]
Hello I still got the same issue with a fresh install. Have you upload the changes? I'm using version ionic2-module-template@0.0.11

**Comment by mlynch** [comment]
Hey I missed some readme changes, use ionic-module-template instead, it's at 0.0.12 (I changed the name) will update this weekend

Get Outlook for iOS




On Thu, Nov 24, 2016 at 3:45 PM -0600, "juansaab" <notifications@github.com> wrote:












Hello I still got the same issue with a fresh install. Have you upload the changes? I'm using version ionic2-module-template@0.0.11

**Comment by juansaab** [comment]
I installed ionic-module-template 0.0.12 instead and now works (on livereload and build prod as well)

**Comment by Yermo** [comment]
I am still unable to get this to work. What I have been trying to accomplish is to create a module managed in a separate git repository that I can then reference in my main app. 

I am getting the same error in my own code that I am getting when I try to reference this module template from an app generated by 'ionic start --v2'.

I was wondering if maybe you could point me in the right direction. 

I am running the latest ionic (as of 2016-11-25 12:15PM).
```
$ ionic -v
2.1.13
```
I create a clean test project.
```
$ ionic start ModuleTest --v2
```

The resulting project has an error in package.json which I reported here (https://github.com/driftyco/ionic-app-scripts/issues/361). Modifying package.json to change two script lines allows the project to run. 
```
"watch": "ionic-app-scripts watch",
"serve:before": "watch"
```
I can then run:
```
$ ionic serve
```

The test project works and I see the sample app in an auto-launched browser as expected.

I clone the ionic2-module-template repository into a directory outside of my test project.

```
$ cd ..
$ git clone https://github.com/driftyco/ionic2-module-template.git
```
Then I build the module:
```
$ cd ionic2-module-template
$ npm install
$ npm run-script build 
```
I notice the distribution files in ./dist
```
$ ls dist/
components  index.js      index.metadata.json    my-module.module.js      my-module.module.metadata.json  providers
index.d.ts  index.js.map  my-module.module.d.ts  my-module.module.js.map  package.json
```
I set up the npm link.
```
$ sudo npm link
```
I switch to my ModuleTest and set up the link there:
```
$ cd ../ModuleTest
$ npm link ionic2-module-template
```
I notice that there is a ionic2-module-template entry in node_modules pointing to the cloned repository.
```
$ ls node_modules/ionic2-module-template
aot  dist  LICENSE  node_modules  package.json  README.md  scripts  src  tsconfig.json
```
I modify 'src/app/app.module.ts' in the generated ModuleTest app to import MyModule.
```
import { MyModule} from 'ionic2-module-template';
```
I also add MyModule to the imports:[] array.
```
  imports: [
    IonicModule.forRoot(MyApp),
    MyModule
  ],
```
Running 'ionic serve' now generates a white screen of death.
Entering 'c' in the ionic console app generate the following error message:
```
0     678747   error    Error: Unexpected value 'MyModule' imported by the module 'AppModule', http://localhost:8100/build/main.js line 1142 > eval, Line: 241
```
Now I suspect that I am not referencing the compiled module code in 'dist' so I tried using:
```
import {MyModule} from 'ionic2-module-template/dist';
```
This generated the same error.
I noticed that there is a published version of the module on npm so I tried that. 
```
$ npm install ionic2-module-template
```
This also produced the same error. (using import { MyModule } from 'ionic2-module-template';)

If, however, I check out the repository directly into the src directory of my app and reference it by path (without building it) everything works as expected. My suspicion is that the tsc compiler in this case is able to find the source files and then incorporate all those symbols in the resulting build.

So what's the correct way of including a module like this when checked out from git?

When I check out a module from git (referenced from a package.json) is there a 'best practice' for auto-building the checked out module?  

I am running under Ubuntu 14.04.1 LTS.

```
$ ionic info

ModuleTest$ vi src/app/app.module.ts 
yml@cylon:~/Projects/ModuleTest$ ionic info

Your system information:

Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.13
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.45
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 3.13
Node Version: v5.6.0
Xcode version: Not installed
```

**Comment by mlynch** [comment]
Npm linked modules don't work in Our webpack setup. Publish to npm first then try that 👍🏼

**Comment by mlynch** [comment]
Also the module name changed to ionic-module-template

**Comment by Yermo** [comment]
Ah. Ok. Thank you for the reply. I did notice the name change and just tried that. npm install of ionic-module-template works for me like a champ. I was going to report that using npm link gives a 
```
0     611419   error    Error: Cannot find module "@angular/platform-browser", http://localhost:8100/build/main.js line 4892 > eval, Line: 2
```
error.

What is the recommended approach for managing proprietary code? I am not able to publish to npm.

**Comment by mlynch** [comment]
Ah, good point. So, generally if you want to use npm with private code, you'll need to use npm private packages or run your own npm enterprise instance. That, or you might be able to use a private github repo and npm install that repo...

**Comment by Yermo** [comment]
Yea, I'm running gitlab here and what I had originally wanted to do was install the module from the gitlab repository, but there are a number of problems with that. I'm looking at installing a private npm server (https://www.npmjs.com/package/sinopia) and seeing if that might work.

Not being able to npm link a module that I'm working on makes the development workflow quite clumsy. What's the issue with webpack that prevents an npm link from working? (i.e. is this fixable or inherent in the packaging design?)

**Comment by mlynch** [comment]
It's fixable but was a limitation of webpack that both us and angular CLI shared. We should have a fix soon

**Comment by tatemz** [comment]
@mlynch - Is there a known fix as of today?
