### ISSUE TITLE
Problem with fresh install ionic2-module-template@0.0.11

### ISSUE THREAD

**Issue by juansaab** [driftyco/ionic2-module-template#6]
Hello,

Just after installing `npm install ionic2-module-template --save` I followed the instructions to import using import { MyModule } from 'ionic2-module-template'; and MyModule inside imports of the app. However when building or running via ionic serve I got:

`Unexpected value 'MyModule' imported by the module 'AppModule'`

I have greats expectations on using this to solve a problem that I had importing a custom Angular2 module. Hope to share my advances.

My enviroment is:

```
Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.13
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.45
ios-deploy version: 1.9.0 
ios-sim version: 5.0.11 
OS: OS X El Capitan
Node Version: v6.9.1
Xcode version: Xcode 8.1 Build version 8B62
```

**Comment by mlynch** [comment]
Hi, use `npm install ionic-module-template`. I neglected to update the readme as the package and module name changed.
