### ISSUE TITLE
Is this repo not supported anymore by the Ionic team anymore ?

### ISSUE THREAD

**Issue by raparlasiva** [driftyco/ionic2-module-template#9]

**Comment by martinpritchardelevate** [comment]
I was wondering about the activity on this too? I've just written a quick post on my attempt at sharing code in an ionic2 app [here](https://medium.com/@blewpri/sharing-logic-between-ionic2-apps-f06feaf51fad#.d52qtxk0b) if anyone is interested.

**Comment by lincolnthree** [comment]
Also looking for how to do this. @martinpritchardelevate, I read your article, wondering why you decided not to continue with the npm module approach, and what your other approach looks like now.

**Comment by mlynch** [comment]
We'd love some community contributions on it. We support it but we're busy.

Would love your thoughts on this PR: https://github.com/driftyco/ionic-module-template/pull/10

Locking this issue
